### ISSUE TITLE
question regarding "combineReducers" method parameters

### ISSUE THREAD

**Issue by yairEO** [ankita1010/react-combine-reducers#1]
Why do you need property names (`reducerOne` / `reducertwo`) ?

```
const [rootReducerCombined, initialStateCombined] = combineReducers({
		reducerOne: [reducerOne, initialStateOne],
		reducertwo: [reducerTwo, initialStateTwo]
	})
```

why not write it as:

```
const [rootReducerCombined, initialStateCombined] = combineReducers(
		[reducerOne, initialStateOne],
		[reducerTwo, initialStateTwo]
	)
```

**Comment by himayand21** [comment]
Hi yairEO.

Passing the [reducer, initialState] as parameters and not as a mapped object would mean the user will not be able to access them with some key.
Right now, the reducers and the stores are segregated based on these keys and would help state management as a whole.

If there is some use case where your suggested approach would be helpful, you can send that right here.

**Comment by ankita1010** [comment]
Hi @yairEO 
Thanks for raising the first issue 😊. Please refer to @himayand21 's take on the same.
Hi @himayand21 
Thank you so much for your response. You wrote an excellent explanation there.

**Comment by AdnanTheExcellent** [comment]
I have a use case where this would be helpful. I have an ecommerce store, and i have a reducer for an Order object for our frontend. 

a very simplified interface of what my Order looks like:

```
interface Order {
  lineItems: LineItem[]
  total: number;
}
```

Then i have an admin section, where i have an AdminOrder, which is the interface of the Order but with extra admin fields that the user never interacts with. A simplified example:

```
interface AdminExtension {
  comments: string;
  cost: number;
  production_ state: string;
}

interface AdminOrder extends Order, AdminExtension {}
```

My front end has a reducer for the Order. I want my backend to have have the same reducer, but with extended options

```
const [adminOrderReducer, initialAdminOrder] = combineReducers(
		[orderReducer, InitialOrder],
		[adminExtensionReducer, initialAdminExtension]
	)
```

**Comment by AdnanTheExcellent** [comment]
In addition, lets say my Order and AdminOrder were the same interface: Order. I now have two reducers: one for my frontend, and one that combines the frontend reducer with other state changes i want only the admin to have access to. would i be able to use this library to do that?
