### ISSUE TITLE
Typescript: here's how to type the state of the combined reducers

### ISSUE THREAD

**Issue by headwinds** [ankita1010/react-combine-reducers#3]
@ankita1010 awesome library - I used it this morning with Typescript and I just wanted to provide some documentation that you might consider adding to your readme or a wiki page:

1. Since there is no @types/react-combine-reducers package yet, all you need to do is edit your .d.ts and add 

```
declare module 'react-combine-reducers'
``` 

2. So how do I type it now? Here is an example combining 2 reducers. I'll put the all types and initial config below but in the end you would probably import them from separate files.

```
type StateA = {
  greet :string
}

type StateB = {
  count :number
}

type CombinedReducerState = {
  stateA: StateA,
  stateB: StateB
}

type CombinedReducerAction = {
  type: string,
  payload?:any
}

const intialAState: StateA = {
  greeting: "hello"
};

const stateAReducer = (
  state: StateA,
  action: { type: string; payload: string }
) => {
  const { type } = action;

  switch (type) {
    case "translate":
      return { ...state, greeting: payload };
    default:
      return state;
  }
};

const intialBState: StateB = {
  count: 0
};

const stateBReducer = (
  state: StateB,
  action: { type: string; payload: number }
) => {
  const { type } = action;

  switch (type) {
    case "incrementCount":
      return { ...state, count: payload };
    default:
      return state;
  }
};


type CombinedReducerType = (state: CombinedReducerState, action: CombinedReducerAction) => CombinedReducerState;

const [rootReducerCombined, initialStateCombined] = combineReducers({
    stateA: [stateAReducer, initialAState],
    stateB: [stateBReducer, initialBState] });

const [{ stateA, stateB }, dispatch] = useReducer<CombinedReducerType>(rootReducerCombined, initialStateCombined);
```

**Comment by ankita1010** [comment]
Hi @headwinds 
This is wonderful. That you so much for the information. Would you like to raise a PR for the same?

**Comment by headwinds** [comment]
@ankita1010 yes love to - I'll try to clean it up a bit and add it to the bottom of your readme for **Typescript Support** - it's really neat what you've done - it's like writing redux without redux

**Comment by ankita1010** [comment]
@headwinds 
That's great! Looking forward to get a PR from you.
Also, thanks for your comments.
