### ISSUE TITLE
State Object Comparison

### ISSUE THREAD

**Issue by tjmoses** [ankita1010/react-combine-reducers#9]
https://github.com/ankita1010/react-combine-reducers/blob/master/src/utility.js#L27

For the below code from the link above,
`
hasStateChanged = hasStateChanged || nextStateForCurrentKey !== prevStateForCurrentKey;
`
I would recommend using a better object comparison technique. Using === or !== compares to see if they are at the same location in memory/identical (since a js object is a reference type). You need to compare if they are equivalent. 

Lodash has a great library for deep object comparisons. 
https://lodash.com/docs/4.17.15#isEqual

**Comment by ankita1010** [comment]
Completely agree with you, shallow comparison does not ensure stopping of unnecessary state updates which results in re rendering. Thanks a lot for pointing this out @tjmoses .

**Comment by jaybe78** [comment]
Hi @ankita1010 Are you gonna do what @tjmoses suggested any time soon ?

**Comment by ChuckJonas** [comment]
I'd disagree with this.. If you are properly maintaining immutable structures then this isn't an issue.
